version: "3"

services:
  bot:
    build: .
    restart: always
    env_file:
      - ./.env
    volumes:
      - ./db:/var/discordtts/db
      - ./emoji-ja:/var/discordtts/emoji-ja
    network_mode: host
